# Generated by Django 3.0.5 on 2023-09-02 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='My_project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='СТИР')),
                ('full_text', models.TextField(verbose_name='Аудиторлик ташкилотининг номи')),
                ('data', models.DateField(verbose_name='Реестрга киритиш санаси ')),
                ('phone', models.CharField(max_length=13, verbose_name='СТИР')),
                ('url_site', models.CharField(max_length=250, verbose_name='СТИР')),
            ],
            options={
                'verbose_name': 'проект',
                'verbose_name_plural': 'проектЫ',
            },
        ),
        migrations.AlterModelOptions(
            name='my_news',
            options={'verbose_name': 'новасть', 'verbose_name_plural': 'новасти'},
        ),
    ]
