# Generated by Django 3.0.5 on 2023-09-02 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20230903_0010'),
    ]

    operations = [
        migrations.AddField(
            model_name='my_project',
            name='gmail',
            field=models.CharField(default=1, max_length=100, verbose_name='почта'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='my_project',
            name='full_text',
            field=models.CharField(max_length=250, verbose_name='Аудиторлик ташкилотининг номи'),
        ),
        migrations.AlterField(
            model_name='my_project',
            name='phone',
            field=models.CharField(max_length=13, verbose_name='номер'),
        ),
        migrations.AlterField(
            model_name='my_project',
            name='url_site',
            field=models.CharField(max_length=250, verbose_name='ссылка'),
        ),
    ]
