# Generated by Django 3.0.5 on 2023-09-13 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20230903_0030'),
    ]

    operations = [
        migrations.CreateModel(
            name='My_stat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='название статьи ')),
                ('full_text', models.TextField(verbose_name='статья')),
                ('data', models.DateField(verbose_name='время выхода статьи')),
            ],
            options={
                'verbose_name': 'статья',
                'verbose_name_plural': 'статьи',
            },
        ),
        migrations.RenameModel(
            old_name='My_project',
            new_name='My_news_project',
        ),
        migrations.AlterField(
            model_name='my_news',
            name='data',
            field=models.DateField(verbose_name='время выхода новости'),
        ),
        migrations.AlterField(
            model_name='my_news',
            name='full_text',
            field=models.TextField(verbose_name='новость'),
        ),
        migrations.AlterField(
            model_name='my_news',
            name='title',
            field=models.CharField(max_length=250, verbose_name='название новости '),
        ),
    ]
