# Generated by Django 3.0.5 on 2023-09-13 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20230913_1011'),
    ]

    operations = [
        migrations.CreateModel(
            name='This_project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stir', models.CharField(max_length=100, verbose_name='СТИР')),
                ('names', models.CharField(max_length=250, verbose_name='Ташкилотининг номи')),
                ('text', models.CharField(max_length=250, verbose_name='Хлоса')),
                ('data', models.DateField(verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'проект',
                'verbose_name_plural': 'проектЫ',
            },
        ),
    ]
