# Generated by Django 3.0.5 on 2023-09-13 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_this_project'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='this_project',
            options={'verbose_name': 'проект_', 'verbose_name_plural': 'проектЫ_'},
        ),
    ]
