# Generated by Django 3.0.5 on 2023-09-13 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20230913_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='this_project',
            name='img',
            field=models.ImageField(default=1, upload_to='media/'),
            preserve_default=False,
        ),
    ]
