# Generated by Django 3.0.5 on 2023-09-13 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_this_project_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='my_news_project',
            name='img',
            field=models.ImageField(default=1, upload_to='media/'),
            preserve_default=False,
        ),
    ]
