# Generated by Django 3.0.5 on 2023-09-13 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_my_news_project_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newe_comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, verbose_name='имя')),
                ('full_text', models.CharField(max_length=70, verbose_name='коментарий')),
            ],
            options={
                'verbose_name': 'коментарий',
                'verbose_name_plural': 'коментарии',
            },
        ),
    ]
