# Generated by Django 3.0.5 on 2023-09-14 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_newe_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='this_project',
            old_name='img',
            new_name='img1',
        ),
        migrations.AddField(
            model_name='this_project',
            name='img2',
            field=models.ImageField(default=1, upload_to='media/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='this_project',
            name='img3',
            field=models.ImageField(default=1, upload_to='media/'),
            preserve_default=False,
        ),
    ]
