# Generated by Django 3.0.5 on 2023-09-14 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20230914_1620'),
    ]

    operations = [
        migrations.RenameField(
            model_name='this_project',
            old_name='img1',
            new_name='project_img1',
        ),
        migrations.RenameField(
            model_name='this_project',
            old_name='img2',
            new_name='project_img2',
        ),
        migrations.RenameField(
            model_name='this_project',
            old_name='img3',
            new_name='project_img3',
        ),
    ]
