# Generated by Django 3.0.5 on 2023-09-14 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20230914_1624'),
    ]

    operations = [
        migrations.RenameField(
            model_name='my_news_project',
            old_name='img',
            new_name='project_img1',
        ),
        migrations.AddField(
            model_name='my_news_project',
            name='project_img2',
            field=models.ImageField(default=1, upload_to='media/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='my_news_project',
            name='project_img3',
            field=models.ImageField(default=1, upload_to='media/'),
            preserve_default=False,
        ),
    ]
